config/routes.rb
Rails.application.routes.draw do
  resources :characters
  get 'adventure', to: 'adventure#create_and_research'
  post 'adventure', to: 'game_sessions#create'
  get 'adventure/:id', to: 'adventure#show'
  put 'adventure/:id', to: 'adventure#update'
  post 'adventure/character', to: 'adventure#create'
  post 'adventure/end_day/:id', to: 'adventure#end_day'
  get 'game_sessions', to: 'game_sessions#index'
  get 'profile/:id', to: 'profile#show'
  post 'character/add_character_to_session/:id', to: 'profile#add_character_to_session'
  get 'roleplay', to: 'roleplay#index'
  devise_for :users
  root 'home#index'
  get 'opinions', to: 'opinions#new'
  post 'opinions', to: 'opinions#create'
  post 'comments', to: 'comments#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :game_session, optional: true
  validates :pseudo, uniqueness: true
  belongs_to :user
  belongs_to :roleplay
  has_many :primary_specs
  has_many :secondary_specs
  has_many :inventories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/game_session.rb
class GameSession < ApplicationRecord
  validates :title, uniqueness: true

  belongs_to :roleplay
  belongs_to :creator, class_name: "User"
  has_many :opinions
  has_many :roles
  has_many :characters
  has_many :users, through: :roles
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :character
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
  belongs_to :game_session
end

app/models/primary_spec.rb
class PrimarySpec < ApplicationRecord
  belongs_to :character
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :game_session
end

app/models/roleplay.rb
class Roleplay < ApplicationRecord
  has_one_attached :roleplay_image
  has_many :characters
  has_many :game_session
end

app/models/secondary_spec.rb
class SecondarySpec < ApplicationRecord
  belongs_to :character
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :pseudo, uniqueness: true

  has_many :characters
  has_many :comments
  has_many :opinions
  has_many :own_sessions, class_name: "GameSession", foreign_key: "creator_id"
  has_many :roles
  has_many :game_sessions, through: :roles
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/adventure_helper.rb
module AdventureHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/roleplay_helper.rb
module RoleplayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdopteUnRoliste</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://use.fontawesome.com/c010389991.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body>
  <div class="navbar-bg-color">
    <%= render 'shared/navbar' %>
  </div>
  <main>
    <%= yield %>
  </main>
</body>
</html>

app/views/shared/_navbar.html.erb
<div class="scrollToTop circle"><i class="fa fa-angle-up"></i></div>

<!-- page wrapper start -->
<!-- ================ -->
<div class="page-wrapper">
  <!-- header-container start -->
  <div class="header-container">
    <!-- header-top start -->
    <!-- classes:  -->
    <!-- "dark": dark version of header top e.g. class="header-top dark" -->
    <!-- "colored": colored version of header top e.g. class="header-top colored" -->
    <!-- ================ -->
    <div class="header-top">
      <% if notice %>
          <div class="alert alert-success col-md-2 m-0"><%= notice %></div>
      <% end %>
      <% if alert %>
          <div class="alert alert-danger col-md-2 m-0"><%= alert %></div>
      <% end %>
      <% if flash["validate"] %>
        <div class="alert alert-success col-md-2 m-0"><%= flash["validate"] %></div>
      <% end %>

      <% if flash["error"] %>
          <div class="alert alert-danger col-md-2 m-0"><%= flash["error"] %></div>
      <% end %>
      <div class="dropdown">
        <a class="dropbtn"><%= image_tag "avatar.png", class:"avatar" %></a>
        <div class="dropdown-content">
          <% if user_session %>
            <%= link_to "Mon profil", "/profile/#{current_user.id}"%>
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Se connecter", new_user_session_path %>
            <%= link_to "S'enregistrer", new_user_registration_path %>
          <% end %>
        </div>
      </div>
    </div>
    <header class="header dark fixed fixed-desktop clearfix">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-auto hidden-md-down">
            <div class="col-lg-10 ml-auto">
              <div class="header-second clearfix">
                <div class="main-navigation main-navigation--mega-menu  animated">
                  <nav class="navbar navbar-expand-lg navbar-light p-0">

                    <div class="collapse navbar-collapse" id="navbar-collapse-1">
                      <ul class="navbar-nav ml-xl-auto">
                        <li>
                          <%= link_to "Les Univers", roleplay_path, class: "nav-link"  %>
                        </li>
                        <!-- mega-menu start -->
                        <li>
                          <%= link_to root_path do %>
                          <%= image_tag "logo2.png", class: "logo_nav" %>
                          <% end %>
                        </li>
                        <!-- mega-menu end -->
                        <li>
                          <%= link_to "Partir à l'aventure", '/adventure', class: "nav-link"  %>
                        </li>
                      </ul>
                      <!-- main-menu end -->
                    </div>
                  </nav>
                </div>
                <!-- main-navigation end -->
              </div>
              <!-- header-second end -->

            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- header end -->
  </div>
</div>
</div>