config/routes.rb
Rails.application.routes.draw do
  resources :characters
  get 'adventure', to: 'adventure#create_and_research'
  post 'adventure', to: 'game_sessions#create'
  get 'adventure/:id', to: 'adventure#show'
  put 'adventure/:id', to: 'adventure#update'
  post 'adventure/character', to: 'adventure#create'
  post 'adventure/end_day/:id', to: 'adventure#end_day'
  get 'game_sessions', to: 'game_sessions#index'
  get 'profile/:id', to: 'profile#show'
  post 'character/add_character_to_session/:id', to: 'profile#add_character_to_session'
  get 'roleplay', to: 'roleplay#index'
  devise_for :users
  root 'home#index'
  get 'opinions', to: 'opinions#new'
  post 'opinions', to: 'opinions#create'
  post 'comments', to: 'comments#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :game_session, optional: true
  validates :pseudo, uniqueness: true
  belongs_to :user
  belongs_to :roleplay
  has_many :primary_specs
  has_many :secondary_specs
  has_many :inventories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/game_session.rb
class GameSession < ApplicationRecord
  validates :title, uniqueness: true

  belongs_to :roleplay
  belongs_to :creator, class_name: "User"
  has_many :opinions
  has_many :roles
  has_many :characters
  has_many :users, through: :roles
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :character
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
  belongs_to :game_session
end

app/models/primary_spec.rb
class PrimarySpec < ApplicationRecord
  belongs_to :character
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :user
  belongs_to :game_session
end

app/models/roleplay.rb
class Roleplay < ApplicationRecord
  has_one_attached :roleplay_image
  has_many :characters
  has_many :game_session
end

app/models/secondary_spec.rb
class SecondarySpec < ApplicationRecord
  belongs_to :character
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :pseudo, uniqueness: true

  has_many :characters
  has_many :comments
  has_many :opinions
  has_many :own_sessions, class_name: "GameSession", foreign_key: "creator_id"
  has_many :roles
  has_many :game_sessions, through: :roles
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :user_signed_in?

  def new
    @character = Character.new
    @game_sessions = Array.new
    current_user.game_sessions.each do |game_session|
      if current_user.roles.find_by(game_session: game_session, game_master: "f")
        unless current_user.characters.find_by(game_session: game_session)
          @game_sessions << game_session
        end
      end
    end
    @roleplays = Roleplay.all
  end

  def show
    if params[:id]
      if Character.find(params[:id])
        @character = Character.find(params[:id])
      end
    end
  end

  def create

    error = Hash.new

    character = Character.new
    character_info = params[:character]

    character.pseudo = character_info["pseudo"]
    character.level = character_info["level"].to_i
    character.description = character_info["description"]
    character.roleplay = Roleplay.find(character_info[:roleplay])
    unless character_info[:game_session] === "none"
      if GameSession.find_by(id: character_info[:game_session])
        character.game_session = GameSession.find(character_info[:game_session])
      end
    end
    character.user = current_user

    if character.save
      error[:character] = "Character Error"
    end
    if params[:primnames]
      params[:primnames].each do |index, value|
        prim = PrimarySpec.new
        prim.name = value
        prim.value = params[:primvals][index].to_i
        prim.character = character
        if prim.save
          error[:prim] = "Prim Error"
        end
      end
    end

    if params[:secnames]
      params[:secnames].each do |index, value|
        sec = SecondarySpec.new
        sec.name = value
        sec.value = params[:secvals][index].to_i
        sec.character = character
        if sec.save
          error[:sec] = "Sec Error"
        end
      end
    end

    if params[:items]
      params[:items].each do |index, value|
        inventory = Inventory.new
        inventory.name = value
        inventory.character = character
        if inventory.save
          error[:item] = "Item Error"
        end
      end
    end

    if error = {}
      redirect_to "/profile/#{current_user.id}", flash: { validate: "Personnage créé !"}
    else
      p error
    end

  end

  private

  def character_params
  	params.require(:character).permit(:pseudo, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :user_exist?

  def show
    @user = User.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(recipient_id: params[:id])
    @character = Character.new
  end

  def add_character_to_session
    character = Character.find(params[:character][:id])
    character.game_session_id = params[:character][:game_session]
    character.save
    redirect_to "/profile/#{params[:id]}", flash: { validate: "Personnage ajouté !" }
  end
  private

  def user_exist?
    if params[:id]
      unless User.find_by(id: params[:id])
        redirect_to root_path
      end
    end
  end
end

app/helpers/adventure_helper.rb
module AdventureHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/game_sessions_helper.rb
module GameSessionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/roleplay_helper.rb
module RoleplayHelper
end

app/views/characters/new.html.erb
<div class="characterbackground pt-5">
  <div class="scrollToTop circle"><i class="fa fa-angle-up"></i></div>
  <div class="page-wrapper">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-auto">
          <div class="hc-element-invisible" data-animation-effect="fadeInDownSmall" data-effect-delay="100">
            <div class="form-block p-30 light-gray-bg border-clear">
              <h2 class="title">Creation de ton personnage</h2>
              <%= form_for @character, url: characters_path  do |f| %>
              <form class="form-horizontal">
                <div class="form-group has-feedback row">
                  <label for="user_pseudo" class="col-md-3 control-label text-md-right col-form-label">Nom</label><span class="text-danger small">*</span><br />
                  <div class="col-md-8">
                    <%= f.text_field :pseudo, class:"form-control", id: "inputUserName", placeholder: "Nom du personnage", autofocus: true, autocomplete: "pseudo" %>
                  </div>
                </div>

                <div class="form-group has-feedback row">
                  <label for="user_pseudo" class="col-md-3 control-label text-md-right col-form-label">Niveau</label><span class="text-danger small">*</span><br />
                  <div class="col-md-8">
                    <%= f.text_field :level, class:"form-control", id: "inputUserLevel", placeholder: "Niveau du personnage", autofocus: true, autocomplete: "level" %>
                  </div>
                </div>

                <% unless @game_sessions === [] %>
                  <div class="form-group has-feedback row">
                    <label for="user_pseudo" class="col-md-3 control-label text-md-right col-form-label">Session de jeux</label><span class="text-danger small">*</span><br />
                    <div class="col-md-8">
                      <select name="character[game_session]" class="select-custom">
                        <option value="none">Sélectionner une session de jeu</option>
                        <% @game_sessions.each do |game_session| %>
                          <option value="<%= game_session.id %>"><%= game_session.title %></option>
                        <% end %>
                      </select>
                    </div>
                  </div>
                <% end %>

                <div class="form-group has-feedback row">
                  <label for="user_pseudo" class="col-md-3 control-label text-md-right col-form-label">Jeux de Rôle</label><span class="text-danger small">*</span><br />
                  <div class="col-md-8">
                    <select name="character[roleplay]" class="select-custom">
                      <% @roleplays.each do |roleplay| %>
                        <option value="<%= roleplay.id %>"><%= roleplay.name %></option>
                      <% end %>
                    </select>
                  </div>
                </div>

                <div class="form-group has-feedback row">
                  <label for="user_email" class="col-md-3 control-label text-md-right col-form-label">Histoire</label><span class="text-danger small">*</span><br />
                  <div class="col-md-8">
                    <%= f.text_area :description, class: "form-control", id: "inputDescription", placeholder: "Retranscrit l'histoire de ton personnage", autofocus: true, autocomplete: "description" %>
                  </div>
                </div>

                <button id="additional-primary-stat" class="btn btn-info mt-3" type="button" name="statp">+</button> Ajouter une caractéristique principale (ex: santé...)

                <div id="input-primary-stat">

                </div>

                <button id="additional-secondary-stat" class="btn btn-info mt-3" type="button" name="statsec">+</button> Ajouter une caractéristique secondaire (ex: force, intelligence...)

                <div id="input-secondary-stat">

                </div>

                <button id="additional-item" class="btn btn-info mt-3" type="button" name="inventory">+</button> Ajouter un item à votre inventaire

                <div id="input-item">

                </div>



                <div class="form-group row">
                  <div class="ml-md-auto col-md-9">
                    <%= f.submit "Creer", class: "btn btn-group btn-default btn-animated" %>
                  </div>
                </div>
              </form>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/characters/show.html.erb
<ul id="info_character">
  <li>Pseudo :<%= @character.pseudo %></li>
  <li>Level :<%= @character.level %></li>
  <li>lore :<%= @character.description %></li>
</ul>
<ul id="primary_specs">
  <% compteur = 0 %>
  <% @character.primary_specs.each do |primary_spec| %>
    <li><%= primary_spec.name %> : <%= primary_spec.value %></li>
  <% end %>
</ul>
<ul id="secondary_specs">
  <% compteur = 0 %>
  <% @character.secondary_specs.each do |secondary_spec| %>
    <li><%= secondary_spec.name %> : <%= secondary_spec.value %></li>
  <% end %>
</ul>
<ul id="items_inventory">
  <% compteur = 0 %>
  <% @character.inventories.each do |inventory| %>
    <li><%= inventory.name %></li>
  <% end %>
</ul>
<div id="link_profile">
  <%= link_to "Profil de #{@character.user.pseudo}", "/profile/#{@character.user.id}" %>
</div>